# version for docker-machine
version: '3'
services:
  web:
#    build: .
    image: "sv99/snt-vector_joomla_web"
    container_name: snt-vector_joomla_web_1
    ports:
      - "8080:80"
    volumes:
      - "/Users/svolkov/work/php/snt-vector_joomla/public_html:/var/www/html"

  mysql:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: snt-vector_joomla_mysql_1
    environment:
      MYSQL_ROOT_PASSWORD: service
      MYSQL_DATABASE: a0236142_app_joomla_0
    volumes:
#      - "/Users/svolkov/work/php/snt-vector_joomla/mysql_data:/var/lib/mysql"
      - "/Users/svolkov/work/php/snt-vector_joomla/backup:/backup"
