version: '3'
services:
  web:
    build: .
    container_name: snt-vector_joomla_web_1
    ports:
      - "8080:80"
    volumes :
      - "./public_html:/var/www/html"

  mysql:
    image: "mysql:5.7"
    container_name: snt-vector_joomla_mysql_1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: service
      MYSQL_DATABASE: a0236142_app_joomla_0
    volumes:
#      - "./mysql_data:/var/lib/mysql"
      - "./backup:/backup"
